pip install --upgrade attrs                 
pip install --upgrade certifi               
pip install --upgrade cffi                  
pip install --upgrade charset-normalizer    
pip install --upgrade dnspython             
pip install --upgrade docopt                
pip install --upgrade docutils              
pip install --upgrade fett                  
pip install --upgrade idna                  
pip install --upgrade more-itertools        
pip install --upgrade networkx              
pip install --upgrade numpy                 
pip install --upgrade packaging             
pip install --upgrade pip                   
pip install --upgrade pluggy                
pip install --upgrade py                    
pip install --upgrade pycparser             
pip install --upgrade pymongo               
pip install --upgrade pyparsing             
pip install --upgrade pytest                
pip install --upgrade python-jsonrpc-server 
pip install --upgrade PyYAML                
pip install --upgrade requests              
pip install --upgrade rstcheck              
pip install --upgrade setuptools            
pip install --upgrade snooty-lextudio       
pip install --upgrade tcod                  
pip install --upgrade tk                    
pip install --upgrade toml                  
pip install --upgrade typing_extensions     
pip install --upgrade ujson                 
pip install --upgrade urllib3               
pip install --upgrade watchdog              
pip install --upgrade wcwidth               
pip install --upgrade wheel                 
